<?php
$PRODUCTION = true;

if($PRODUCTION){
  define("COBI_MYSQL_SERVER", "HOSTNAME");
  define("COBI_MYSQL_USERNAME", "USERNAME");
  define("COBI_MYSQL_PASSWORD", "PASSWORD");
  define("COBI_MYSQL_DATABASE", "DATABASENAME");
}else{
  define("COBI_MYSQL_SERVER", "HOSTNAME");
  define("COBI_MYSQL_USERNAME", "USERNAME");
  define("COBI_MYSQL_PASSWORD", "PASSWORD");
  define("COBI_MYSQL_DATABASE", "DATABASENAME");
}
?>
